### ISSUE TITLE
regression after update to `1.1.0`

### ISSUE THREAD

**Issue by evilebottnawi** [syntax-tree/mdast-comment-marker#4]
I use `remark-message-control` for disable linting on some files and `no-file-name-irregular-characters` rule to validate filenames.

Before update no errors for `remark-link` for this file:

**CODE_OF_CONDUCT.md**

```
<!-- lint disable -->

My custom syntax where linting is disabled.
```

Now it is doesn't work and `remark-lint` throw error `Do not use `_` in a file name  no-file-name-irregular-characters  remark-lint`

**Comment by ChristianMurphy** [comment]
See https://github.com/remarkjs/remark-lint/issues/198

**Comment by wooorm** [comment]
🤔 did this really ever work? I thought file-path related messages could never be turned off inline?

**Comment by evilebottnawi** [comment]
@wooorm work before update

**Comment by wooorm** [comment]
@evilebottnawi I don‘t see how this could change due to https://github.com/syntax-tree/mdast-comment-marker/commit/1900f4a74c6d7de9aff8e9628da7fcfef69883ac... 🤔 So I’m closing this.

Weird though! Did something else change in your setup? Maybe it’s an issue somewhere else?
